QUAL_LEVELS = {
    "Junior": 0.7,
    "Middle": 1.0,
    "Senior": 1.4,
}

SECTOR_BASE = {
    "it": 30000,
    "medicine": 23000,
    "law": 26000,
    "business": 27000,
    "engineering": 24000,
    "science": 22000,
    "science_education": 18000,
    "media": 23000,
    "creative": 19000,
    "transport": 22000,
    "manual_technical": 22000,
    "manual": 19000,
    "industry": 23000,
    "service": 22000,
    "security": 21000,
    "agriculture": 21000,
    "sport": 22000,
    "public": 22000,
    "office": 24000,
    "other": 20000,
}

JOB_FACTORS = {
    "Єгер": {
        "cluster": "agriculture",
        "salary_coef": 1.2,
        "popularity_coef": 0.4,
        "allowed_locations": {"village", "urban_settlement", "city"},
    },
    "Інженер": {
        "cluster": "engineering",
        "salary_coef": 1.7,
        "popularity_coef": 1.0,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Історик": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Агроном": {
        "cluster": "agriculture",
        "salary_coef": 1.4,
        "popularity_coef": 0.8,
        "allowed_locations": {"village", "urban_settlement"},
    },
    "Адвокат": {
        "cluster": "law",
        "salary_coef": 2.1,
        "popularity_coef": 0.7,
        "allowed_locations": {"city", "capital"},
    },
    "Актор": {
        "cluster": "creative",
        "salary_coef": 1.5,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Акушер": {
        "cluster": "medicine",
        "salary_coef": 1.8,
        "popularity_coef": 0.5,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Антрополог": {
        "cluster": "science",
        "salary_coef": 1.4,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Археолог": {
        "cluster": "science",
        "salary_coef": 1.4,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Архітектор": {
        "cluster": "engineering",
        "salary_coef": 1.9,
        "popularity_coef": 0.7,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Астронавт": {
        "cluster": "other",
        "salary_coef": 3.0,
        "popularity_coef": 0.05,
        "allowed_locations": {"capital", "remote"},
    },
    "Астроном": {
        "cluster": "science",
        "salary_coef": 1.9,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Астрофізик": {
        "cluster": "science",
        "salary_coef": 2.1,
        "popularity_coef": 0.1,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Ботанік": {
        "cluster": "science",
        "salary_coef": 1.3,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Бухгалтер": {
        "cluster": "office",
        "salary_coef": 1.5,
        "popularity_coef": 1.3,
        "allowed_locations": {"urban_settlement", "city", "capital", "remote"},
    },
    "Бібліограф": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Бібліотекар": {
        "cluster": "science_education",
        "salary_coef": 1.0,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Бізнесмен": {
        "cluster": "business",
        "salary_coef": 2.0,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital"},
    },
    "Біолог": {
        "cluster": "science",
        "salary_coef": 1.5,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Ветеринар": {
        "cluster": "medicine",
        "salary_coef": 1.5,
        "popularity_coef": 0.7,
        "allowed_locations": {"village", "urban_settlement", "city"},
    },
    "Випробувач": {
        "cluster": "engineering",
        "salary_coef": 1.6,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Водій": {
        "cluster": "transport",
        "salary_coef": 1.0,
        "popularity_coef": 1.4,
        "allowed_locations": {"village", "urban_settlement", "city", "capital"},
    },
    "Вчитель": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 1.4,
        "allowed_locations": {"village", "urban_settlement", "city", "capital"},
    },
    "Візажист": {
        "cluster": "service",
        "salary_coef": 1.2,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Географ": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Геолог": {
        "cluster": "science",
        "salary_coef": 1.6,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Геофізик": {
        "cluster": "science",
        "salary_coef": 1.8,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Головний меркшейдер": {
        "cluster": "engineering",
        "salary_coef": 2.0,
        "popularity_coef": 0.1,
        "allowed_locations": {"city", "capital"},
    },
    "Графік": {
        "cluster": "creative",
        "salary_coef": 1.4,
        "popularity_coef": 0.6,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Громадський діяч": {
        "cluster": "public",
        "salary_coef": 1.3,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Гінеколог": {
        "cluster": "medicine",
        "salary_coef": 2.2,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital"},
    },
    "Гірник": {
        "cluster": "industry",
        "salary_coef": 1.4,
        "popularity_coef": 0.6,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Гірничий інженер": {
        "cluster": "engineering",
        "salary_coef": 1.9,
        "popularity_coef": 0.4,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Дантист": {
        "cluster": "medicine",
        "salary_coef": 2.1,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Державний службовець": {
        "cluster": "public",
        "salary_coef": 1.4,
        "popularity_coef": 1.0,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Детектив": {
        "cluster": "security",
        "salary_coef": 1.6,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Дизайнер": {
        "cluster": "creative",
        "salary_coef": 1.5,
        "popularity_coef": 1.0,
        "allowed_locations": {"urban_settlement", "city", "capital", "remote"},
    },
    "Дипломат": {
        "cluster": "public",
        "salary_coef": 2.0,
        "popularity_coef": 0.2,
        "allowed_locations": {"capital", "remote"},
    },
    "Диригент": {
        "cluster": "creative",
        "salary_coef": 1.8,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Доцент": {
        "cluster": "science_education",
        "salary_coef": 1.7,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Драматург": {
        "cluster": "creative",
        "salary_coef": 1.6,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Ді-джей": {
        "cluster": "service",
        "salary_coef": 1.3,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Економіст": {
        "cluster": "office",
        "salary_coef": 1.7,
        "popularity_coef": 1.0,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Електрик": {
        "cluster": "manual_technical",
        "salary_coef": 1.3,
        "popularity_coef": 1.1,
        "allowed_locations": {"village", "urban_settlement", "city", "capital"},
    },
    "Електромонтажник": {
        "cluster": "manual_technical",
        "salary_coef": 1.3,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Електромонтер": {
        "cluster": "manual_technical",
        "salary_coef": 1.3,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Електрослюсар": {
        "cluster": "manual_technical",
        "salary_coef": 1.3,
        "popularity_coef": 0.7,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Електротехнік": {
        "cluster": "engineering",
        "salary_coef": 1.6,
        "popularity_coef": 0.7,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Епідеміолог": {
        "cluster": "medicine",
        "salary_coef": 1.8,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Етнограф": {
        "cluster": "science",
        "salary_coef": 1.3,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Живописець": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Журналіст": {
        "cluster": "media",
        "salary_coef": 1.5,
        "popularity_coef": 0.9,
        "allowed_locations": {"city", "capital"},
    },
    "Золотар": {
        "cluster": "manual_technical",
        "salary_coef": 1.6,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Зоолог": {
        "cluster": "science",
        "salary_coef": 1.3,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Каскадер": {
        "cluster": "creative",
        "salary_coef": 1.7,
        "popularity_coef": 0.1,
        "allowed_locations": {"city", "capital"},
    },
    "Клавішник": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Клоун": {
        "cluster": "service",
        "salary_coef": 1.0,
        "popularity_coef": 0.3,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Композитор": {
        "cluster": "creative",
        "salary_coef": 1.8,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Конструктор": {
        "cluster": "engineering",
        "salary_coef": 1.7,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital"},
    },
    "Краєзнавець": {
        "cluster": "science_education",
        "salary_coef": 1.1,
        "popularity_coef": 0.3,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Круп'є": {
        "cluster": "service",
        "salary_coef": 1.4,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Кур'єр": {
        "cluster": "service",
        "salary_coef": 0.9,
        "popularity_coef": 1.2,
        "allowed_locations": {"village", "urban_settlement", "city", "capital"},
    },
    "Кухар": {
        "cluster": "service",
        "salary_coef": 1.0,
        "popularity_coef": 1.2,
        "allowed_locations": {"village", "urban_settlement", "city", "capital"},
    },
    "Кушнір": {
        "cluster": "manual_technical",
        "salary_coef": 1.2,
        "popularity_coef": 0.3,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Кіноактор": {
        "cluster": "creative",
        "salary_coef": 1.6,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Кінокритик": {
        "cluster": "media",
        "salary_coef": 1.3,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Кінолог": {
        "cluster": "service",
        "salary_coef": 1.2,
        "popularity_coef": 0.5,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Кінорежисер": {
        "cluster": "creative",
        "salary_coef": 1.9,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Локсмайстер": {
        "cluster": "manual_technical",
        "salary_coef": 1.2,
        "popularity_coef": 0.3,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Льотчик": {
        "cluster": "transport",
        "salary_coef": 2.4,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Лікар": {
        "cluster": "medicine",
        "salary_coef": 2.0,
        "popularity_coef": 0.9,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Літературознавець": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "М'ясник": {
        "cluster": "manual",
        "salary_coef": 1.0,
        "popularity_coef": 0.7,
        "allowed_locations": {"village", "urban_settlement", "city"},
    },
    "Маркетолог": {
        "cluster": "office",
        "salary_coef": 1.5,
        "popularity_coef": 0.9,
        "allowed_locations": {"city", "capital"},
    },
    "Математик": {
        "cluster": "science",
        "salary_coef": 1.6,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Машиніст": {
        "cluster": "transport",
        "salary_coef": 1.3,
        "popularity_coef": 0.7,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Медик": {
        "cluster": "medicine",
        "salary_coef": 1.6,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Менеджер": {
        "cluster": "office",
        "salary_coef": 1.5,
        "popularity_coef": 1.2,
        "allowed_locations": {"urban_settlement", "city", "capital", "remote"},
    },
    "Мистецтвознавець": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Мовознавець": {
        "cluster": "science_education",
        "salary_coef": 1.3,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Модель": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Модельєр": {
        "cluster": "creative",
        "salary_coef": 1.5,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Музикант": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.7,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Музикознавець": {
        "cluster": "science_education",
        "salary_coef": 1.3,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Музичний редактор": {
        "cluster": "media",
        "salary_coef": 1.4,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Мікробіолог": {
        "cluster": "science",
        "salary_coef": 1.6,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Мінералог": {
        "cluster": "science",
        "salary_coef": 1.5,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Мірошник": {
        "cluster": "industry",
        "salary_coef": 1.0,
        "popularity_coef": 0.3,
        "allowed_locations": {"village", "urban_settlement"},
    },
    "Намотувальник": {
        "cluster": "industry",
        "salary_coef": 1.0,
        "popularity_coef": 0.4,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Науковець": {
        "cluster": "science",
        "salary_coef": 1.8,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Нотаріус": {
        "cluster": "law",
        "salary_coef": 2.2,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Няня": {
        "cluster": "service",
        "salary_coef": 0.9,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Паблік рилейшнз": {
        "cluster": "media",
        "salary_coef": 1.5,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital"},
    },
    "Палеонтолог": {
        "cluster": "science",
        "salary_coef": 1.5,
        "popularity_coef": 0.1,
        "allowed_locations": {"city", "capital"},
    },
    "Паралегал": {
        "cluster": "law",
        "salary_coef": 1.4,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Парфюмер": {
        "cluster": "industry",
        "salary_coef": 1.4,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Патологоанатом": {
        "cluster": "medicine",
        "salary_coef": 2.0,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Педагог": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 1.1,
        "allowed_locations": {
            "village",
            "urban_settlement",
            "city",
            "capital",
            "remote",
        },
    },
    "Пекар": {
        "cluster": "service",
        "salary_coef": 1.0,
        "popularity_coef": 0.9,
        "allowed_locations": {"village", "urban_settlement", "city", "capital"},
    },
    "Перекладач": {
        "cluster": "office",
        "salary_coef": 1.4,
        "popularity_coef": 0.7,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Петрограф": {
        "cluster": "science",
        "salary_coef": 1.5,
        "popularity_coef": 0.1,
        "allowed_locations": {"city", "capital"},
    },
    "Письменник": {
        "cluster": "creative",
        "salary_coef": 1.5,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Правник": {
        "cluster": "law",
        "salary_coef": 1.7,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital"},
    },
    "Провізор": {
        "cluster": "medicine",
        "salary_coef": 1.6,
        "popularity_coef": 0.6,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Програміст": {
        "cluster": "it",
        "salary_coef": 2.0,
        "popularity_coef": 1.0,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Продюсер": {
        "cluster": "media",
        "salary_coef": 1.9,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Прокурор": {
        "cluster": "law",
        "salary_coef": 2.2,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Промисловець": {
        "cluster": "business",
        "salary_coef": 1.8,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Професор": {
        "cluster": "science_education",
        "salary_coef": 1.9,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Психолог": {
        "cluster": "service",
        "salary_coef": 1.5,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city", "capital", "remote"},
    },
    "Публіцист": {
        "cluster": "media",
        "salary_coef": 1.4,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Піаніст": {
        "cluster": "creative",
        "salary_coef": 1.4,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Підприємець": {
        "cluster": "business",
        "salary_coef": 2.0,
        "popularity_coef": 0.7,
        "allowed_locations": {"urban_settlement", "city", "capital", "remote"},
    },
    "Пілот": {
        "cluster": "transport",
        "salary_coef": 2.5,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Реабілітолог": {
        "cluster": "medicine",
        "salary_coef": 1.4,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital"},
    },
    "Редактор": {
        "cluster": "media",
        "salary_coef": 1.4,
        "popularity_coef": 0.7,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Режисер": {
        "cluster": "creative",
        "salary_coef": 1.8,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Реставратор": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Ріелтор": {
        "cluster": "service",
        "salary_coef": 1.5,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Різноробочий": {
        "cluster": "manual",
        "salary_coef": 0.9,
        "popularity_coef": 1.0,
        "allowed_locations": {"village", "urban_settlement", "city"},
    },
    "Сантехнік": {
        "cluster": "manual_technical",
        "salary_coef": 1.2,
        "popularity_coef": 0.9,
        "allowed_locations": {"village", "urban_settlement", "city"},
    },
    "Секретар": {
        "cluster": "office",
        "salary_coef": 1.0,
        "popularity_coef": 0.9,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Складальник": {
        "cluster": "industry",
        "salary_coef": 1.0,
        "popularity_coef": 0.9,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Скульптор": {
        "cluster": "creative",
        "salary_coef": 1.4,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Слідчий": {
        "cluster": "security",
        "salary_coef": 1.7,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Соціолог": {
        "cluster": "science_education",
        "salary_coef": 1.4,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Співак": {
        "cluster": "creative",
        "salary_coef": 1.5,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Стиліст": {
        "cluster": "service",
        "salary_coef": 1.3,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital"},
    },
    "Стоматолог": {
        "cluster": "medicine",
        "salary_coef": 2.2,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Стропальник": {
        "cluster": "industry",
        "salary_coef": 1.1,
        "popularity_coef": 0.5,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Сценарист": {
        "cluster": "creative",
        "salary_coef": 1.5,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Фармацевт": {
        "cluster": "medicine",
        "salary_coef": 1.5,
        "popularity_coef": 0.8,
        "allowed_locations": {"urban_settlement", "city", "capital"},
    },
    "Фермер": {
        "cluster": "agriculture",
        "salary_coef": 1.3,
        "popularity_coef": 0.7,
        "allowed_locations": {"village", "urban_settlement"},
    },
    "Флорист": {
        "cluster": "service",
        "salary_coef": 1.1,
        "popularity_coef": 0.5,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Фольклорист": {
        "cluster": "science_education",
        "salary_coef": 1.2,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Фотограф": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.7,
        "allowed_locations": {"urban_settlement", "city", "capital", "remote"},
    },
    "Фрілансер": {
        "cluster": "other",
        "salary_coef": 1.3,
        "popularity_coef": 0.8,
        "allowed_locations": {
            "village",
            "urban_settlement",
            "city",
            "capital",
            "remote",
        },
    },
    "Футболіст": {
        "cluster": "sport",
        "salary_coef": 2.3,
        "popularity_coef": 0.2,
        "allowed_locations": {"city", "capital"},
    },
    "Фізик": {
        "cluster": "science",
        "salary_coef": 1.7,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Філолог": {
        "cluster": "science_education",
        "salary_coef": 1.3,
        "popularity_coef": 0.6,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Хореограф": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.4,
        "allowed_locations": {"city", "capital"},
    },
    "Художник": {
        "cluster": "creative",
        "salary_coef": 1.3,
        "popularity_coef": 0.7,
        "allowed_locations": {"city", "capital", "remote"},
    },
    "Хімік": {
        "cluster": "science",
        "salary_coef": 1.6,
        "popularity_coef": 0.5,
        "allowed_locations": {"city", "capital"},
    },
    "Швачка": {
        "cluster": "manual",
        "salary_coef": 0.9,
        "popularity_coef": 0.9,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Шериф": {
        "cluster": "security",
        "salary_coef": 1.6,
        "popularity_coef": 0.1,
        "allowed_locations": {"capital"},
    },
    "Штукатур": {
        "cluster": "manual",
        "salary_coef": 1.0,
        "popularity_coef": 0.7,
        "allowed_locations": {"urban_settlement", "city"},
    },
    "Ювелір": {
        "cluster": "manual_technical",
        "salary_coef": 1.6,
        "popularity_coef": 0.3,
        "allowed_locations": {"city", "capital"},
    },
    "Юрист": {
        "cluster": "law",
        "salary_coef": 1.8,
        "popularity_coef": 0.9,
        "allowed_locations": {"city", "capital"},
    },
    "Ґрунтознавець": {
        "cluster": "agriculture",
        "salary_coef": 1.4,
        "popularity_coef": 0.3,
        "allowed_locations": {"village", "urban_settlement", "city"},
    },
}
