from dataclasses import dataclass


@dataclass(frozen=True)
class ClusterSalaryConfig:
    delay_prob: float
    delay_days_min: int
    delay_days_max: int

    bonus_prob: float
    bonus_share_mean: float
    bonus_share_std: float

    penalty_prob: float
    penalty_share_mean: float
    penalty_share_std: float


CLUSTER_CONFIG: dict[str, ClusterSalaryConfig] = {
    "industry": ClusterSalaryConfig(
        delay_prob=0.07,
        delay_days_min=5,
        delay_days_max=30,
        bonus_prob=0.25,
        bonus_share_mean=0.15,
        bonus_share_std=0.08,
        penalty_prob=0.10,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "engineering": ClusterSalaryConfig(
        delay_prob=0.05,
        delay_days_min=3,
        delay_days_max=25,
        bonus_prob=0.30,
        bonus_share_mean=0.15,
        bonus_share_std=0.07,
        penalty_prob=0.08,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "manual_technical": ClusterSalaryConfig(
        delay_prob=0.05,
        delay_days_min=3,
        delay_days_max=20,
        bonus_prob=0.25,
        bonus_share_mean=0.12,
        bonus_share_std=0.06,
        penalty_prob=0.10,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "manual": ClusterSalaryConfig(
        delay_prob=0.04,
        delay_days_min=2,
        delay_days_max=20,
        bonus_prob=0.20,
        bonus_share_mean=0.10,
        bonus_share_std=0.05,
        penalty_prob=0.12,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "it": ClusterSalaryConfig(
        delay_prob=0.01,
        delay_days_min=1,
        delay_days_max=10,
        bonus_prob=0.50,
        bonus_share_mean=0.20,
        bonus_share_std=0.10,
        penalty_prob=0.05,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "office": ClusterSalaryConfig(
        delay_prob=0.02,
        delay_days_min=1,
        delay_days_max=10,
        bonus_prob=0.40,
        bonus_share_mean=0.18,
        bonus_share_std=0.08,
        penalty_prob=0.06,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "business": ClusterSalaryConfig(
        delay_prob=0.02,
        delay_days_min=1,
        delay_days_max=10,
        bonus_prob=0.45,
        bonus_share_mean=0.22,
        bonus_share_std=0.10,
        penalty_prob=0.07,
        penalty_share_mean=0.07,
        penalty_share_std=0.04,
    ),
    "service": ClusterSalaryConfig(
        delay_prob=0.03,
        delay_days_min=1,
        delay_days_max=15,
        bonus_prob=0.35,
        bonus_share_mean=0.15,
        bonus_share_std=0.08,
        penalty_prob=0.10,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "medicine": ClusterSalaryConfig(
        delay_prob=0.04,
        delay_days_min=2,
        delay_days_max=20,
        bonus_prob=0.30,
        bonus_share_mean=0.12,
        bonus_share_std=0.06,
        penalty_prob=0.08,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "public": ClusterSalaryConfig(
        delay_prob=0.05,
        delay_days_min=5,
        delay_days_max=25,
        bonus_prob=0.25,
        bonus_share_mean=0.10,
        bonus_share_std=0.05,
        penalty_prob=0.06,
        penalty_share_mean=0.04,
        penalty_share_std=0.02,
    ),
    "science": ClusterSalaryConfig(
        delay_prob=0.03,
        delay_days_min=2,
        delay_days_max=15,
        bonus_prob=0.25,
        bonus_share_mean=0.10,
        bonus_share_std=0.05,
        penalty_prob=0.05,
        penalty_share_mean=0.04,
        penalty_share_std=0.02,
    ),
    "science_education": ClusterSalaryConfig(
        delay_prob=0.03,
        delay_days_min=2,
        delay_days_max=15,
        bonus_prob=0.20,
        bonus_share_mean=0.08,
        bonus_share_std=0.04,
        penalty_prob=0.05,
        penalty_share_mean=0.03,
        penalty_share_std=0.02,
    ),
    "media": ClusterSalaryConfig(
        delay_prob=0.03,
        delay_days_min=2,
        delay_days_max=15,
        bonus_prob=0.30,
        bonus_share_mean=0.15,
        bonus_share_std=0.08,
        penalty_prob=0.08,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "transport": ClusterSalaryConfig(
        delay_prob=0.04,
        delay_days_min=2,
        delay_days_max=20,
        bonus_prob=0.25,
        bonus_share_mean=0.12,
        bonus_share_std=0.06,
        penalty_prob=0.08,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "agriculture": ClusterSalaryConfig(
        delay_prob=0.04,
        delay_days_min=3,
        delay_days_max=20,
        bonus_prob=0.25,
        bonus_share_mean=0.10,
        bonus_share_std=0.05,
        penalty_prob=0.09,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "security": ClusterSalaryConfig(
        delay_prob=0.04,
        delay_days_min=2,
        delay_days_max=15,
        bonus_prob=0.20,
        bonus_share_mean=0.08,
        bonus_share_std=0.04,
        penalty_prob=0.10,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
    "creative": ClusterSalaryConfig(
        delay_prob=0.03,
        delay_days_min=2,
        delay_days_max=20,
        bonus_prob=0.35,
        bonus_share_mean=0.18,
        bonus_share_std=0.10,
        penalty_prob=0.10,
        penalty_share_mean=0.07,
        penalty_share_std=0.04,
    ),
    "sport": ClusterSalaryConfig(
        delay_prob=0.03,
        delay_days_min=2,
        delay_days_max=20,
        bonus_prob=0.40,
        bonus_share_mean=0.25,
        bonus_share_std=0.15,
        penalty_prob=0.12,
        penalty_share_mean=0.10,
        penalty_share_std=0.06,
    ),
    "other": ClusterSalaryConfig(
        delay_prob=0.03,
        delay_days_min=2,
        delay_days_max=15,
        bonus_prob=0.25,
        bonus_share_mean=0.12,
        bonus_share_std=0.06,
        penalty_prob=0.08,
        penalty_share_mean=0.05,
        penalty_share_std=0.03,
    ),
}