"""delete external_id

Revision ID: 21e5c05d8780
Revises: 30c02b2dec9d
Create Date: 2025-11-25 21:56:45.144400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21e5c05d8780"
down_revision: Union[str, Sequence[str], None] = "30c02b2dec9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_external_id"), table_name="employees")
    op.drop_column("employees", "external_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("external_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_employees_external_id"), "employees", ["external_id"], unique=False
    )
    # ### end Alembic commands ###
