"""add models

Revision ID: 30c02b2dec9d
Revises: 6c304a3283ee
Create Date: 2025-11-25 11:07:36.339413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c02b2dec9d'
down_revision: Union[str, Sequence[str], None] = '6c304a3283ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('first_name_en', sa.String(), nullable=True),
    sa.Column('middle_name_en', sa.String(), nullable=True),
    sa.Column('second_name_en', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address_uk', sa.String(), nullable=True),
    sa.Column('address_en', sa.String(), nullable=True),
    sa.Column('populated_type', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('working_email', sa.String(), nullable=True),
    sa.Column('working_phone', sa.String(), nullable=True),
    sa.Column('contract_payment', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_external_id'), 'employees', ['external_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'qualification', 'address', name='uq_job')
    )
    op.create_table('salaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'month', name='uq_salary_employee_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salaries')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_employees_external_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
